name: Event print
on: [push, workflow_dispatch]

permissions: read-all

jobs:
  print:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Print event
      run: |
        echo "$ACTIONS_ID_TOKEN_REQUEST_URL"
        echo "$ACTIONS_ID_TOKEN_REQUEST_TOKEN"
        #echo "event: $GITHUB_EVENT_NAME"
        #cat "$GITHUB_EVENT_PATH"
