name: Event print
on: [push, workflow_dispatch]

permissions: read-all

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - name: Print event
      run: |
        cat "event: $GITHUB_EVENT_NAME"
        cat "$GITHUB_EVENT_PATH"
