name: Test SLSA
on:
  workflow_dispatch:
  push:
    tags:
      - "*" 

permissions: read-all
      
jobs:
  args:
    runs-on: ubuntu-latest
    outputs:
      ldflags: ${{ steps.ldflags.outputs.value }}
    steps:
      - id: checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.3.4
        with:
          fetch-depth: 0
      - id: ldflags
        run: |
          echo "::set-output name=value::$(./scripts/version-ldflags)"

  build:
    permissions:
      id-token: write
      contents: read
    needs: args
    #uses: gossts/slsa-go/.github/workflows/builder.yml@main
    uses: laurentsimon/slsa-go/.github/workflows/builder.yml@feat/stdinerr
    with:
      go-version: 1.17
      env: "VERSION_LDFLAGS:${{needs.args.outputs.ldflags}}"

  upload:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: 'actions/download-artifact@v2'
        with:
          name: ${{ needs.build.outputs.go-binary-name }}
      - run: |
          echo name is ${{ needs.build.outputs.go-binary-name }}
          pwd
          ls
          chmod a+x ./${{ needs.build.outputs.go-binary-name }}
          ./${{ needs.build.outputs.go-binary-name }} --help
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ needs.build.outputs.go-binary-name }}
